"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

export default function PrescriptionsPage() {
  const [prescriptions, setPrescriptions] = useState<any[]>([]);
  const [patients, setPatients] = useState<any[]>([]);
  const [showAdd, setShowAdd] = useState(false);
  const [loading, setLoading] = useState(false);

  const [form, setForm] = useState({
    patient_id: "",
    medicine: "",
    dosage: "",
    duration: "",
    notes: ""
  });

  useEffect(() => {
    loadPrescriptions();
    loadPatients();
  }, []);

  async function loadPrescriptions() {
    try {
      const res = await fetch("/api/prescriptions");
      const data = await res.json();
      if (data && !data.error) setPrescriptions(data);
    } catch (err) {
      console.error(err);
    }
  }

  async function loadPatients() {
    try {
      const res = await fetch("/api/patients");
      const data = await res.json();
      if (data && !data.error) setPatients(data);
    } catch (err) {
      console.error(err);
    }
  }

  async function addPrescription() {
    if (!form.patient_id || !form.medicine) return;
    setLoading(true);
    try {
      const res = await fetch("/api/prescriptions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form)
      });
      const data = await res.json();

      if (data.error) {
        alert("Error: " + data.error.message);
      } else {
        setShowAdd(false);
        setForm({ patient_id: "", medicine: "", dosage: "", duration: "", notes: "" });
        loadPrescriptions();
      }
    } catch (err: any) {
      alert("Failed to fetch: " + err.message);
    }
    setLoading(false);
  }

  const handlePrint = (p: any) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    const html = `
      <html>
        <head>
          <title>Prescription - ${p.patients?.name || 'Patient'}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            .header { border-bottom: 2px solid #3182ce; padding-bottom: 20px; margin-bottom: 30px; }
            .clinic-name { font-size: 24px; font-weight: bold; color: #3182ce; }
            .label { font-weight: bold; color: #718096; text-transform: uppercase; font-size: 12px; }
            .value { font-size: 18px; margin-bottom: 20px; }
            .medicine-box { background: #f7fafc; padding: 20px; border-radius: 8px; border: 1px solid #edf2f7; }
            .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 12px; color: #a0aec0; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="clinic-name">MediCore Clinic Suite</div>
            <div>Medical Prescription</div>
          </div>
          <p><span class="label">Patient Name:</span><br/><span class="value">${p.patients?.name || 'N/A'}</span></p>
          <p><span class="label">Date:</span><br/><span class="value">${new Date(p.created_at).toLocaleDateString()}</span></p>
          <div class="medicine-box">
            <p><span class="label">Medicine:</span><br/><span class="value" style="color:#2d3748; font-weight:bold;">${p.medicine}</span></p>
            <p><span class="label">Dosage:</span><br/><span class="value">${p.dosage}</span></p>
            <p><span class="label">Duration:</span><br/><span class="value">${p.duration}</span></p>
          </div>
          <p><span class="label">Instructions:</span><br/><span class="value">${p.notes || 'No special instructions.'}</span></p>
          <div class="footer">
            Generated by MediCore Clinic Suite • This is a digital prescription.
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `;
    printWindow.document.write(html);
    printWindow.document.close();
  };

  return (
    <div style={{ padding: "2rem", maxWidth: "1200px", margin: "0 auto" }}>
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "2rem" }}>
        <div>
          <h1 style={{ fontSize: "24px", fontWeight: "bold", color: "#2d3748" }}>Prescriptions</h1>
          <p style={{ color: "#718096" }}>Manage medical prescriptions for all patients</p>
        </div>
        <button 
          style={{ background: "#3182ce", color: "white", padding: "10px 20px", borderRadius: "8px", cursor: "pointer", border: "none", fontWeight: "600" }}
          onClick={() => setShowAdd(true)}
        >
          ＋ New Prescription
        </button>
      </header>

      <div style={{ background: "white", padding: "1.5rem", borderRadius: "12px", border: "1px solid #edf2f7", boxShadow: "0 2px 4px rgba(0,0,0,0.05)" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ borderBottom: "2px solid #edf2f7", textAlign: "left" }}>
              <th style={{ padding: "1rem", color: "#718096", fontSize: "0.875rem" }}>PATIENT</th>
              <th style={{ padding: "1rem", color: "#718096", fontSize: "0.875rem" }}>MEDICINE</th>
              <th style={{ padding: "1rem", color: "#718096", fontSize: "0.875rem" }}>DOSAGE</th>
              <th style={{ padding: "1rem", color: "#718096", fontSize: "0.875rem" }}>DURATION</th>
              <th style={{ padding: "1rem", color: "#718096", fontSize: "0.875rem" }}>ACTION</th>
            </tr>
          </thead>
          <tbody>
            {prescriptions.length === 0 ? (
              <tr><td colSpan={5} style={{ padding: "2rem", textAlign: "center", color: "#a0aec0" }}>No prescriptions found.</td></tr>
            ) : (
              prescriptions.map((p) => (
                <tr key={p.id} style={{ borderBottom: "1px solid #edf2f7" }}>
                  <td style={{ padding: "1rem", fontWeight: "600", color: "#2d3748" }}>{p.patients?.name || 'N/A'}</td>
                  <td style={{ padding: "1rem", color: "#3182ce", fontWeight: "600" }}>{p.medicine}</td>
                  <td style={{ padding: "1rem", color: "#4a5568" }}>{p.dosage}</td>
                  <td style={{ padding: "1rem", color: "#4a5568" }}>{p.duration}</td>
                  <td style={{ padding: "1rem" }}>
                    <button 
                      onClick={() => handlePrint(p)}
                      style={{ background: "#edf2f7", border: "none", padding: "6px 12px", borderRadius: "6px", cursor: "pointer", color: "#3182ce", fontSize: "0.875rem", fontWeight: "600" }}
                    >
                      Print 🖨️
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showAdd && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 }}>
          <div style={{ background: "white", padding: "30px", borderRadius: "12px", width: "100%", maxWidth: "500px", boxShadow: "0 20px 25px -5px rgba(0,0,0,0.1)" }}>
            <h2 style={{ marginBottom: "1.5rem" }}>New Prescription</h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
              <div>
                <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "600", color: "#4a5568", fontSize: "0.875rem" }}>Patient</label>
                <select 
                  style={{ width: "100%", padding: "10px", border: "1px solid #e2e8f0", borderRadius: "8px" }}
                  value={form.patient_id}
                  onChange={(e) => setForm({ ...form, patient_id: e.target.value })}
                >
                  <option value="">Select Patient</option>
                  {patients.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                </select>
              </div>
              <div>
                <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "600", color: "#4a5568", fontSize: "0.875rem" }}>Medicine Name</label>
                <input 
                  style={{ width: "100%", padding: "10px", border: "1px solid #e2e8f0", borderRadius: "8px" }} 
                  placeholder="e.g. Paracetamol"
                  value={form.medicine} 
                  onChange={e => setForm({...form, medicine: e.target.value})} 
                />
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                <div>
                  <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "600", color: "#4a5568", fontSize: "0.875rem" }}>Dosage</label>
                  <input 
                    style={{ width: "100%", padding: "10px", border: "1px solid #e2e8f0", borderRadius: "8px" }} 
                    placeholder="e.g. 500mg"
                    value={form.dosage} 
                    onChange={e => setForm({...form, dosage: e.target.value})} 
                  />
                </div>
                <div>
                  <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "600", color: "#4a5568", fontSize: "0.875rem" }}>Duration</label>
                  <input 
                    style={{ width: "100%", padding: "10px", border: "1px solid #e2e8f0", borderRadius: "8px" }} 
                    placeholder="e.g. 5 days"
                    value={form.duration} 
                    onChange={e => setForm({...form, duration: e.target.value})} 
                  />
                </div>
              </div>
              <div>
                <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "600", color: "#4a5568", fontSize: "0.875rem" }}>Instructions</label>
                <textarea 
                  style={{ width: "100%", padding: "10px", border: "1px solid #e2e8f0", borderRadius: "8px", minHeight: "80px" }} 
                  placeholder="Take after meals..."
                  value={form.notes} 
                  onChange={e => setForm({...form, notes: e.target.value})} 
                />
              </div>
            </div>
            <div style={{ display: "flex", gap: "10px", marginTop: "2rem" }}>
              <button onClick={() => setShowAdd(false)} style={{ flex: 1, padding: "12px", borderRadius: "8px", border: "1px solid #e2e8f0", background: "white", cursor: "pointer", fontWeight: "600" }}>Cancel</button>
              <button 
                onClick={addPrescription} 
                disabled={loading} 
                style={{ flex: 1, padding: "12px", borderRadius: "8px", background: "#38a169", color: "white", border: "none", cursor: "pointer", fontWeight: "600" }}
              >
                {loading ? "Saving..." : "Save Prescription"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}